### ISSUE TITLE
Replace samalba/dockerclient with engine-api/client

### ISSUE THREAD

**Issue by sayboras** [machine-drivers/machine#26]
As mentioned in https://github.com/docker/swarm/issues/1879, https://github.com/samalba/dockerclient is outdated and no longer maintained.

The official client is available here https://github.com/moby/moby/tree/master/client

**Comment by afbjorklund** [comment]
Already reported as https://github.com/docker/machine/issues/3943

**Comment by sayboras** [comment]
Closed this issue as it's already tracked upstream
